#!/usr/bin/perl

use Selenium::Chrome;
use JSON;
use File::Slurp;
use Data::Dumper;



my $driver = Selenium::Chrome->new(
  extra_capabilities => {
    'goog:chromeOptions' => {
      args => ['headless', 'disable-gpu', 'window-size=1920,1080', 'no-sandbox' ],
        prefs => {
          'download.default_directory' => '/home/vine/files'
      },
    }
  }
);

my $target = "https://vinelink.vineapps.com/search/CA/Person";
$driver->get($target);
my $title = $driver->get_title;
print "title: $title\n";

my ($button, $input, $element,$select, $search_value);
$search_value = 'Rodriguez';

$button = $driver->find_element('//*[@id="vl-menu-options-sign-in-button"]');
if ($button){
    $button->click();
    sleep 3;
    eval {
        $input = $driver->find_element('//*[@id="mat-input-0"]');
print "sendkeys\n";
        $input->send_keys('jozefn777');
        $input = $driver->find_element('//*[@id="mat-input-1"]');
        $input->send_keys('BezelcanopyCar1b');
print "sendkeys\n";
        sleep 3;
        $button = $driver->find_element('//*[@id="vl-login-btn"]');
        $button->submit();
print "subit user/pass \n";
        sleep 2;
        eval{
            $element = $driver->find_element('//*[@id="mat-dialog-2"]/vl-error-dialog/div');
        };
        if (!$@){
           print "Login did not happen\n";
           exit();
        }

    };
    if ($@){
        print "Error with click - $@";  
        die();
    }
}
sleep 3;

print "at select\n";
while(1){
    $element = $driver->find_element('//*[@id="person-search-type-select"]');

    if ($element){
        $driver->execute_script(qq~ var b = document.querySelector('#person-search-type-select');
                                b.click();
                            ~);
        last;
    } else {
        sleep 3;
    }
}
sleep 3;
print "searching\n";
my $action = 0;
while(1){

    $element = $driver->find_element('//*[@id="person-search-type-select-panel"]');
print "element: $element\n";
    if ($element){
        $action->set
        last;
    } else {
        sleep 3;
    }
}

print "at input $search_value\n";

my $found_checkbox = 0;
$action = 0;
while (1){
    $action = $driver->find_element('//*[@id="partial-search-checkbox-input"]');
print " checkbox action: $action\n";
    if ($action){
        $action->set_selected;
        $found_checkbox = 1;
        last;
    } else {
        sleep 3;
    }
}

print "found_checkbox: $found_checkbox\n";

my $js1 = qq~
            var action = 0;
            var b = document.getElementById('person-last-name-input');
            if (b){
                b.value = '$search_value';
                action = 1;
            }
                return action;
    ~;

while (1){
    my $action =0;
    if ($found_checkbox){
        $action = $driver->execute_script($js1);
        print "action: $action\n";
        if ($action){
            last;
        } else {
            sleep 3;
        }
    }
}


print "click search\n";
my $js2 = qq~
            var action = 0;
            if (document.querySelector('#search_button')){
               document.querySelector('#search_button').click();
               action = 1;
            }
            return action;
    ~;

while (1){
    my $action = $driver->execute_script($js2);
    print "action: $action\n";
    if ($action){
        last;
    } else {
        sleep 3;
    }
}
print "before javascript\n";
while(1){
    $action = read_pages();
    last if ( $action eq 'stop');
}

my $js_search_terms = qq{
        var action = 0;
        if (document.querySelector('#person-search-search-terms' ~ div vl-person-not-found') ){
            action = 1;
        }
        return action;
    };

sub read_pages{
    my $no_records_found = 0;
    my $cnt =0;
    my $action;
    while (1){
        $action = $driver->execute_script($js_search_terms);
print " readpages $action\n";
        if ($action){
            $no_records_found = 1;
            last;
        } else {
            sleep 3;
        }
    }
    return 'stop' if ($no_records_found);
    while(1){ 
        print "at creation of download\n";
        $driver->execute_script(qq~
            var tag = "$cnt"; var dfile= '${search_value}_download_'+tag+'.csv';
            var data=[];
            var head=[]; head.push('Name');
            head.push('Facility');
            head.push('ID');
            head.push('Status');
            head.push('Gender');
            data.push(head.join(","));
 
            var person_cards = document.querySelectorAll('html>body>vl-vine-link-app>div>div>main>vl-person-search-results>div>div>vl-person-card');


            for (var i=0;i<person_cards.length;++i){
                var r=[];
                var tag = person_cards[i].querySelector('mat-card>mat-card-title>h2');
                r.push(tag.innerHTML);
                var tag1 = person_cards[i].querySelector('#person-reporting-agency-name');
                if (tag1){
                    r.push(tag1.innerText);
                } else {
                    r.push("No agency");
                }
                var tag2 = person_cards[i].querySelector('#person-person-context-refid-value');
                if (tag2){
                    r.push(tag2.innerText);
                } else {
                    r.push("No id found");
                }
                var tag3 = person_cards[i].querySelector('#person-custody-status-value');
                if (tag3){
                    r.push(tag3.innerText);
                } else {
                    r.push("No status found")
                }
 
                var tag4 = person_cards[i].querySelector('#person-gender-value');
                if (tag4){
                    r.push(tag4.innerText);
                } else {
                    r.push("No Gender Found");
                }
  
                data.push(r.join(","));

            }

        csv_file = new Blob([data.join("")], {type: "text/csv"});

        download_link = document.createElement("a");

        download_link.download = dfile;

        download_link.href = window.URL.createObjectURL(csv_file);

        download_link.style.display = "none";

        document.body.appendChild(download_link);

        download_link.click();

        ~);
        unless (check_continue()){
            last;
        }
    }
    return 'stop';
}

sub check_continue{
    my $tcount = 0;
    my $continue = 0;
    my $js = qq~
       var continue = 0;
       if (document.querySelector('#person-search-pagination-button') ){
          document.querySelector('#person-search-pagination-button').click();
          continue = 1;
       }
       return continue;
    ~;

print "Check for load page button\n";
    while(1){
        $continue =  $driver->execute_script($js);
        if ($continue){
            last;
        } else {
            sleep 3;
            $tcount++;
        }
        if ($tcount > 10){
            $continue = 0;
            last;
        }
    }
    return $continue;
}

sub read_log{
    my $string = Dumper($driver->get_log("browser"));
    print "l: $string\n";
}





