#!/usr/bin/perl

use Selenium::Chrome;
use JSON;
use File::Slurp;
use Data::Dumper;



my $driver = Selenium::Chrome->new(
  extra_capabilities => {
    'goog:chromeOptions' => {
      args => ['headless', 'disable-notifications', 'disable-gpu', 'window-size=1920,1080', 'no-sandbox', 'disable-extensions' ,'start-maximized' ],
        prefs => {
          'download.default_directory' => '/home/vine/files'
      },
    }
  }
);

my $cnt = 0;

my $target = "https://vinelink.vineapps.com/search/CA/Person";
$driver->get($target);
my $title = $driver->get_title;
print "title: $title\n";

my ($button, $input, $element,$select, $search_value);
$search_value = 'Rodriguez';

check_pp($driver);

$driver->capture_screenshot("screenshot".${cnt}++.".png");
if ( element_exists({driver=>$driver,exp=>'//*[@id="vl-menu-options-sign-in-button"]'})){

    check_pp($driver);

    $driver->capture_screenshot("screenshot".${cnt}++.".png");
    $button = $driver->find_element('//*[@id="vl-menu-options-sign-in-button"]');
    $button->click();
    sleep 3;
    $driver->capture_screenshot("screenshot".${cnt}++.".png");
}
if ( element_exists({driver=>$driver,exp=>'//*[@id="mat-input-0"]'})){

    check_pp($driver);

    $driver->capture_screenshot("screenshot".${cnt}++.".png");
    $input = $driver->find_element('//*[@id="mat-input-0"]');
    $input->send_keys('jozefn777');
    $driver->capture_screenshot("screenshot".${cnt}++.".png");
    $input = $driver->find_element('//*[@id="mat-input-1"]');
    $input->send_keys('BezelcanopyCar1b');
    $driver->capture_screenshot("screenshot".${cnt}++.".png");
    sleep 3;
}
if ( element_exists({driver=>$driver,exp=>'//*[@id="vl-login-btn"]'})){
        $driver->capture_screenshot("screenshot".${cnt}++.".png");
        $button = $driver->find_element('//*[@id="vl-login-btn"]');
        $button->submit;
        $driver->capture_screenshot("screenshot".${cnt}++.".png");
        print "subit user/pass \n";
        sleep 2;
}

$driver->capture_screenshot("screenshot".${cnt}++.".png");


if ( element_exists({driver=>$driver,exp=>'//*[@id="person-search-type-select"]'}) ){
     $element = $driver->find_element('//*[@id="person-search-type-select"]/div');
     $element->click;
}

$driver->capture_screenshot("screenshot".${cnt}++.".png");

if ( element_exists({driver=>$driver,exp=>'//*[@id="person-last-name-input"]'}) ){
     $element = $driver->find_element('//*[@id="person-last-name-input"]');
     $driver->capture_screenshot("screenshot".${cnt}++.".png");
     $element->send_keys("$search_value");
     $driver->capture_screenshot("screenshot".${cnt}++.".png");
}
    
print " checkbox search\n";
my $found_checkbox = 0;
$action = 0;
if ( element_exists({driver=>$driver,exp=>'//*[@id="partial-search-checkbox-input"]'}) ){
     $driver->capture_screenshot("screenshot".${cnt}++.".png");
     $action = $driver->find_element('//*[@id="partial-search-checkbox-input"]');
     unless ($action->is_selected){
        $action->set_selected;
        $action->toggle;
     }
     $found_checkbox = 1;
     $driver->capture_screenshot("screenshot".${cnt}++.".png");
}

print "found_checkbox: $found_checkbox\n";


print "click search\n";
if ( element_exists({driver=>$driver,exp=>'//*[@id="search_button"]'}) ){
   $driver->capture_screenshot("screenshot".${cnt}++.".png");
   $action = $driver->find_element('//*[@id="search_button"]');
   $action->submit;
};


        $driver->capture_screenshot("screenshot".${cnt}++.".png");
print "before javascript\n";

if ( element_exists({driver=>$driver,exp=>'//*[@id="pnf-main-header"]'}) ){
    print " no records found \n";
    $driver->shutdown_binary;
    exit();
}

if ( element_exists({driver=>$driver,exp=>'//*[@id="person-search-search-terms"]'}) ){
    my $cnt = 0;
    while(1){ 
        print "at creation of download\n";
        $driver->capture_screenshot("screenshot".${cnt}++.".png");
        $cnt++;
        $driver->execute_script(qq~
	            var tag = "$cnt"; 
                var dfile= '${search_value}_download_'+tag+'.csv';
	            var data=[];
	            var head=[]; head.push('Name');
	            head.push('Facility');
	            head.push('ID');
	            head.push('Status');
	            head.push('Gender');
	            data.push(head.join(","));
	 
	            var person_cards = document.querySelectorAll('html>body>vl-vine-link-app>div>div>main>vl-person-search-results>div>div>vl-person-card');
	
	
	            for (var i=0;i<person_cards.length;++i){
	                var r=[];
	                var tag = person_cards[i].querySelector('mat-card>mat-card-title>h2');
	                r.push(tag.innerHTML);
	                var tag1 = person_cards[i].querySelector('#person-reporting-agency-name');
	                if (tag1){
	                    r.push(tag1.innerText);
	                } else {
	                    r.push("No agency");
	                }
	                var tag2 = person_cards[i].querySelector('#person-person-context-refid-value');
	                if (tag2){
	                    r.push(tag2.innerText);
	                } else {
	                    r.push("No id found");
	                }
	                var tag3 = person_cards[i].querySelector('#person-custody-status-value');
	                if (tag3){
	                    r.push(tag3.innerText);
	                } else {
	                    r.push("No status found")
	                }
	 
	                var tag4 = person_cards[i].querySelector('#person-gender-value');
	                if (tag4){
	                    r.push(tag4.innerText);
	                } else {
	                    r.push("No Gender Found");
	                }
	  
	                data.push(r.join(","));
	
	            }
	
	            csv_file = new Blob([data.join("")], {type: "text/csv"});
	
	            download_link = document.createElement("a");
	
	            download_link.download = dfile;
	
	            download_link.href = window.URL.createObjectURL(csv_file);
	
	            download_link.style.display = "none";
	
	            document.body.appendChild(download_link);
	
	            download_link.click();
	
	        ~);
        my ($continue, $action) = check_continue($driver);
        if ($continue){
            $action->click;
        } else {
                last;
        }
    }
}

sub check_continue{
    my $driver = shift;
    my $continue = 0;
    sleep 3;
    if ( element_exists({driver=>$driver,exp=>'//*[@id="person-search-pagination-button"]'}) ){
       my $action = $driver->find_element('//*[@id="person-search-pagination-button"]');
print " at click\n";
       $continue = 1;
    }
    return ($continue, $action);
}

sub read_log{
    my $string = Dumper($driver->get_log("browser"));
    print "l: $string\n";
}


sub check_spinner{
    my $driver = shift;
    while(1){
        unless ( 
            element_exists({driver=>$driver,exp=>'/html/body/vl-vine-link-app/vl-loader/div/div/div/mat-spinner'}) 
            ){
            last;
        }
        sleep 10;
    }
}


sub element_exists{
    my $args = shift;
    my $driver = $args->{driver};
    my $exp = $args->{exp};
    my $values;
    $values = $driver->find_elements($exp);
    my $cnt = scalar @{$values};
    return ($cnt);
}
    

sub check_pp{
    $driver = shift;
    if ( element_exists({driver=>$driver,exp=>'//*[text()[contains(.,"OK")]]'})){
        $element = $driver->find_element('//*[text()[contains(.,"OK")]]');
        $element->click;
    }

    $driver->capture_screenshot("screenshot".${cnt}++.".png");
    
    if ( element_exists({driver=>$driver,exp=>'//*[text()[contains(.,"Got It")]]'})){
        $element = $driver->find_element('//*[text()[contains(.,"Got It")]]');
        $element->click;
        $element->click;
    }
    $driver->capture_screenshot("screenshot".${cnt}++.".png");
}




